services:
  db:
    image: postgres:17.7
    restart: unless-stopped
    container_name: java_jwt_login_db
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}

    ports:
        - "${DB_PORT}:5432"