CREATE SCHEMA IF NOT EXISTS users;

CREATE TABLE users.countries (
    country_id SMALLSERIAL PRIMARY KEY,
    name VARCHAR(100) NOT NULL,
    iso_code CHAR(2) NOT NULL UNIQUE,
    phone_code CHAR(3) NOT NULL
);

CREATE TABLE users.roles (
    role_id SMALLSERIAL PRIMARY KEY,
    name VARCHAR(20) NOT NULL UNIQUE
);

CREATE TABLE users.permissions (
    permission_id SMALLSERIAL PRIMARY KEY,
    name VARCHAR(25) NOT NULL UNIQUE
);

CREATE TABLE users.users (
    user_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100), -- Opcional
    last_name VARCHAR(100) NOT NULL,
    second_last_name VARCHAR(100), -- Opcional
    email VARCHAR(255) NOT NULL UNIQUE,
    password_hash TEXT NOT NULL,
    telephone_num VARCHAR(50) NOT NULL,
    country_id SMALLINT NOT NULL REFERENCES users.countries(country_id),
    role_id SMALLINT NOT NULL REFERENCES users.roles(role_id),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    is_verified BOOLEAN NOT NULL DEFAULT FALSE,
    verified_at TIMESTAMP WITH TIME ZONE -- Opcional
);

CREATE TABLE users.refresh_tokens (
    refresh_token_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users.users(user_id) ON DELETE CASCADE,
    refresh_token_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
    device_id VARCHAR(255), -- generated by client
    token_family_id VARCHAR(255), -- generated by server
    user_agent TEXT,
    ip_address_hash TEXT
);

CREATE TABLE users.email_verification_tokens (
    token_id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id UUID NOT NULL REFERENCES users.users(user_id) ON DELETE CASCADE,
    token_hash TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE TABLE users.roles_permissions (
    role_id SMALLINT NOT NULL REFERENCES users.roles(role_id) ON DELETE CASCADE,
    permission_id SMALLINT NOT NULL REFERENCES users.permissions(permission_id) ON DELETE CASCADE,
    PRIMARY KEY (role_id, permission_id)
);